import {
  Body,
  Patch,
  Controller,
  Request,
  Get,
  UseGuards,
  Delete,
  Post,
  UseInterceptors,
  UploadedFiles,
  Query,
} from '@nestjs/common';
import { FileFieldsInterceptor } from '@nestjs/platform-express';
import { JwtAuthGuard } from 'src/auth/guards/jwt-auth.guard';
import {
  project_idDto,
  ProjectDto,
  FilterProjectDto,
} from './dtos/project.dto';
import { ProjectService } from './projects.service';
// Multer config
import { multerOptions } from 'src/config/multer.config';

@Controller('project')
export class ProjectController {
  constructor(private readonly projectService: ProjectService) {}

  @Get('user')
  @UseGuards(JwtAuthGuard)
  async getUserProject(@Request() req) {
    return this.projectService.getUserProjects(req.user);
  }

  @Get('all')
  async getAllProject(@Query() filterProjectDto?: FilterProjectDto) {
    // @TODO Remove that
    return [
      {
        id: 42,
        user_id: 1,
        created_at: '2023-01-01T01:05:58.719Z',
        updated_at: '2023-01-01T01:05:58.719Z',
        is_online: true,
        project_name: 'Jon project ',
        starting_on: '2023-10-27T00:00:00.000Z',
        full_name: 'Jon Hualde',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'week',
        description: 'This is a test project',
        difficulty: 'beginner',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 100,
        tools_and_technologies: [1, 3, 5],
        participants_ids: [],
        job_titles_wanted: [2, 5, 8],
        job_titles_filled: [],
        project_main_picture:
          'pictures/c531dd57-1a5f-4140-9516-df1651cb0edb-profile_pic.jpeg',
        attachments: [
          'attachments/3f15f5ba-3ea2-4e1d-86df-50634cf443e3-pic_122857_1_xxl.jpeg',
        ],
      },
      {
        id: 41,
        user_id: 1,
        created_at: '2023-01-01T01:05:35.975Z',
        updated_at: '2023-01-01T01:05:35.975Z',
        is_online: true,
        project_name: 'Jon project 3',
        starting_on: '2023-10-27T00:00:00.000Z',
        full_name: 'Jon Hualde',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'week',
        description: 'This is a test project',
        difficulty: 'beginner',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 100,
        tools_and_technologies: [1, 3, 5],
        participants_ids: [],
        job_titles_wanted: [2, 5, 8],
        job_titles_filled: [],
        project_main_picture:
          'pictures/c5d1ec95-7737-4dcd-9a45-ffdc53d04bfd-instituto-séneca-centro-internacional-de-postgrado.png',
        attachments: [
          'attachments/39ecf959-48de-4786-af83-84a28f0ee332-pic_122857_1_xxl.jpeg',
        ],
      },
      {
        id: 36,
        user_id: 24,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Mr. Calvin Morar',
        starting_on: '2022-06-16T01:35:08.710Z',
        full_name: 'Leonard Lebsack',
        estimated_time_duration: 8,
        estimated_time_duration_metric: 'week',
        description:
          'Corporis nobis unde. Enim velit ea cumque sunt eaque quo voluptatum. Aut nihil neque vel facilis. Minus illum fugit pariatur magnam rerum adipisci. Non assumenda suscipit dolorem voluptate quia sequi soluta ex possimus. Quia cumque incidunt voluptatibus ratione nisi unde repellat quis. Officiis tempore voluptas aspernatur. Rerum officiis ab. Animi ipsum repellat dignissimos voluptas ad nam voluptates illum. Minima eos dicta sed suscipit dicta quis. Quis maiores perferendis harum ullam illum quas placeat. Recusandae dolores dignissimos eveniet hic sit enim accusamus accusamus eum.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 137,
        tools_and_technologies: [5, 6, 8, 9, 7, 1, 2],
        participants_ids: [],
        job_titles_wanted: [3, 15, 7, 2, 13, 8, 4, 10, 12, 14, 6],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 34,
        user_id: 21,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Miss Freddie Jakubowski',
        starting_on: '2022-07-05T17:28:35.373Z',
        full_name: 'Wallace Zieme',
        estimated_time_duration: 10,
        estimated_time_duration_metric: 'week',
        description:
          'Natus adipisci quisquam aperiam velit sapiente alias nesciunt eius quas. Accusantium beatae repudiandae eum. Rerum alias perspiciatis delectus consequuntur nostrum fuga animi. Repellat eaque laboriosam enim ex quidem. Autem voluptatem mollitia ab. Est aut exercitationem ad quis ut eligendi molestiae quae non. Eos et laboriosam voluptatem omnis officiis. Aliquam laboriosam cupiditate ipsa illum in aperiam sit odit perspiciatis. Itaque temporibus a et neque tempora deserunt aut enim. Omnis aut blanditiis omnis corrupti.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: false,
        initial_investment_cost: 47,
        tools_and_technologies: [10, 9, 2, 6],
        participants_ids: [],
        job_titles_wanted: [10, 12, 11],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 37,
        user_id: 26,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Darlene Kohler',
        starting_on: '2022-06-18T12:36:53.091Z',
        full_name: 'Elmer Donnelly',
        estimated_time_duration: 10,
        estimated_time_duration_metric: 'week',
        description:
          'Maiores non doloremque reiciendis eum. A repellendus et deleniti voluptas. Eaque quia dolore facilis blanditiis deleniti ea dicta soluta. Eos libero voluptatem quia eveniet aliquid facere itaque nihil. Optio repellat beatae. Perferendis soluta unde tempora iusto atque id omnis odio aspernatur. Labore fuga dolor odit id et laboriosam ut delectus. Ea voluptatibus pariatur molestiae est quam suscipit itaque. Qui ut unde qui sapiente et autem ut. Minima eius atque. Sunt aliquam id accusamus tempore eum distinctio debitis qui delectus. Nemo consequuntur commodi placeat ipsam qui laudantium eaque.',
        difficulty: 'intermediate',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 75,
        tools_and_technologies: [10, 9, 1, 3, 8],
        participants_ids: [],
        job_titles_wanted: [4, 11, 8, 3, 6, 2, 9, 1, 14, 5, 10, 13, 15],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 35,
        user_id: 31,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Beulah Schaden',
        starting_on: '2022-07-03T22:23:38.295Z',
        full_name: 'Renee Wilkinson',
        estimated_time_duration: 1,
        estimated_time_duration_metric: 'week',
        description:
          'Sit quo similique eos sed quidem fugiat quis. Vero ut debitis. Quidem cumque hic eaque excepturi eos quas possimus. Qui iure voluptate dolorem rerum ad. Molestias et ducimus facere repudiandae veniam eius ut doloremque. Aspernatur fuga hic molestiae. Suscipit corrupti rerum earum itaque a quasi repellat impedit consequatur. Consequatur ipsum molestias quibusdam dolor repudiandae. Enim et et et. Iusto laboriosam autem voluptas eum dolorum eaque hic consequatur. Sint quam consequatur dolorum quia fugiat quod. Eveniet iusto quis. Et nihil alias autem quos alias ullam qui accusantium eligendi.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 25,
        tools_and_technologies: [1, 9, 10, 7, 2, 8, 6, 5, 4],
        participants_ids: [],
        job_titles_wanted: [7, 15, 6, 4, 12, 9, 3, 10],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 31,
        user_id: 17,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Van Daniel',
        starting_on: '2022-07-28T02:07:54.212Z',
        full_name: 'Lance Nikolaus IV',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'week',
        description:
          'Tempora rem quae nam cumque necessitatibus magnam. Ut et fugiat amet ea dolore qui qui et. Voluptas aut perferendis eaque voluptas accusamus iusto nesciunt ea. Eum quasi deserunt quia aliquid eos odit est. Quis molestias quisquam ut voluptatibus numquam sunt molestias eos quod. Veritatis nostrum repellat. Sed quidem animi eos sed debitis. Eos vel ab sit ea sit soluta possimus est aliquam. Non quia vero. Et quas ut eum magni libero. Eos aut dolorem quaerat facilis esse et. Cupiditate aspernatur rerum sequi omnis dolore dolorem eos dolorum vel.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: false,
        initial_investment_cost: 130,
        tools_and_technologies: [1, 7, 2],
        participants_ids: [],
        job_titles_wanted: [8, 3, 14, 4, 10, 11, 9, 5, 7, 12, 6],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 30,
        user_id: 8,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Whitney Bernier',
        starting_on: '2022-07-11T04:58:48.029Z',
        full_name: 'Benjamin Marks',
        estimated_time_duration: 7,
        estimated_time_duration_metric: 'week',
        description:
          'Excepturi impedit architecto illum qui sit velit. Sit molestias excepturi quia at. Perspiciatis ut quasi. Et ut enim ut perferendis. Sint perferendis iusto est quidem cum in ipsam. Voluptatibus nam asperiores at. Aut numquam reiciendis sunt quisquam. Provident molestiae fugiat officiis suscipit. Iure eos atque vero dicta qui praesentium laborum optio repudiandae. Nam ipsum doloribus quaerat. Maxime eum voluptates cum non iste nobis est eos. Nihil et dicta. Non reprehenderit iusto labore ea.',
        difficulty: 'intermediate',
        type: 'training project',
        number_of_participants: 2,
        initial_investment: true,
        initial_investment_cost: 61,
        tools_and_technologies: [7, 1, 5, 4, 10, 6, 2, 3],
        participants_ids: [],
        job_titles_wanted: [15, 8, 6, 2],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 29,
        user_id: 17,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Theresa Beatty',
        starting_on: '2022-07-12T11:39:38.085Z',
        full_name: 'Donna Christiansen',
        estimated_time_duration: 4,
        estimated_time_duration_metric: 'week',
        description:
          'Rerum praesentium id ut voluptates saepe cumque cupiditate magnam. Odio qui quidem praesentium. Quo aliquam eos alias exercitationem officiis laborum ut tenetur nisi. Architecto blanditiis fuga odio repellendus et repudiandae et voluptate. Quibusdam ipsa corrupti velit et pariatur. Sunt porro consequatur repudiandae. Sed eaque voluptatum ut voluptatem impedit. Ipsum minus velit fugit suscipit et facere. Quo dolorem sunt. Aut sunt laborum nihil. Aut assumenda sit sint similique. Iste velit id nihil et reiciendis saepe.',
        difficulty: 'expert',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 62,
        tools_and_technologies: [5, 9, 4, 8, 1, 10, 2],
        participants_ids: [],
        job_titles_wanted: [5],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 27,
        user_id: 24,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Jeffrey Treutel',
        starting_on: '2022-06-21T15:30:26.304Z',
        full_name: 'Darren Morissette',
        estimated_time_duration: 0,
        estimated_time_duration_metric: 'week',
        description:
          'Nesciunt velit quam adipisci ratione. Alias veritatis similique optio. Rerum necessitatibus qui quidem pariatur corrupti. Consequatur enim non. Cumque rerum a nemo itaque vel nemo ex. Eum sed voluptatem aut. Modi saepe dolorem consequuntur consectetur. Voluptas corrupti repellendus inventore esse sed omnis quo. Consequatur ut dolorum iste. Dolor possimus repellendus alias nobis. Saepe excepturi architecto pariatur consequatur. Fugit qui modi quo.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 141,
        tools_and_technologies: [5, 9, 8, 4, 6],
        participants_ids: [],
        job_titles_wanted: [15, 1, 3, 7],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 40,
        user_id: 30,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Joseph West',
        starting_on: '2022-07-31T02:23:58.885Z',
        full_name: 'Stuart Sanford',
        estimated_time_duration: 5,
        estimated_time_duration_metric: 'week',
        description:
          'Voluptatem aut iste incidunt consequuntur et numquam eligendi officiis nisi. Quasi consequatur quo debitis. Suscipit quidem quidem et possimus itaque cumque eligendi. Ratione odio ut dolorem error fugiat placeat eos. Nihil et dolorem molestiae ex nihil. Fuga iure corporis. Cum et maiores enim in veniam est. Eum explicabo delectus sit. Voluptatem qui quod voluptatum et et explicabo vitae natus et. Voluptas rerum blanditiis reprehenderit. Ut perspiciatis alias saepe. Inventore rem illum beatae enim aut quisquam reiciendis eos cum.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 136,
        tools_and_technologies: [8, 6, 5, 3, 2, 7, 10],
        participants_ids: [],
        job_titles_wanted: [8, 12, 2, 14, 5, 4, 6, 1, 13, 10, 11, 7, 9],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 39,
        user_id: 25,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Tasha Luettgen',
        starting_on: '2022-07-22T21:56:39.706Z',
        full_name: 'Thomas Bauch',
        estimated_time_duration: 8,
        estimated_time_duration_metric: 'month',
        description:
          'Optio dignissimos est repellendus id sit id officia aspernatur. Voluptas possimus quia vel eos. Dolores non adipisci dignissimos accusantium debitis at voluptatum dolores quasi. Reprehenderit enim quo sint est hic deleniti quos modi. Officia voluptatem iure enim quibusdam. Placeat nam ullam omnis quaerat inventore quia illum ab. Neque eveniet nihil neque sit sequi sint dolorum voluptas. Provident quo ut saepe reprehenderit non. Quam quis error voluptatem eius laboriosam molestiae quaerat consequatur. Quas omnis cumque vel unde aut fuga mollitia ratione. Laborum at sequi eaque expedita quam fugiat officia.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 111,
        tools_and_technologies: [10, 3, 8, 2, 7, 6, 9, 5],
        participants_ids: [],
        job_titles_wanted: [4, 11, 12, 2, 7],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 33,
        user_id: 30,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Amelia Witting',
        starting_on: '2022-07-04T15:34:00.461Z',
        full_name: 'Mr. Clint Leuschke',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'month',
        description:
          'Dolores vel quidem libero. Eius veritatis illo excepturi. Perspiciatis odio est quam expedita est necessitatibus odit. Aut est fugiat ipsa deleniti sint occaecati voluptatem. Corrupti quod esse voluptatem. Nostrum voluptas unde rerum ad. Enim quam voluptate iure. Laborum animi et. Ut est maiores non soluta aut blanditiis possimus laborum. A praesentium soluta deleniti tempore dolore itaque ducimus. Maxime id commodi voluptas repellendus et qui numquam et.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 119,
        tools_and_technologies: [4, 3, 8, 7, 6],
        participants_ids: [],
        job_titles_wanted: [7, 2, 8, 11, 15, 5, 12, 6],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 38,
        user_id: 3,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Lonnie Wehner',
        starting_on: '2022-06-22T01:40:44.129Z',
        full_name: 'Horace Gibson',
        estimated_time_duration: 1,
        estimated_time_duration_metric: 'week',
        description:
          'Voluptatem facere ullam quisquam vel. Veritatis porro possimus accusantium vel autem mollitia. Omnis officia consectetur debitis unde facilis exercitationem. Fugit fugiat quia cupiditate enim. Sunt blanditiis recusandae et eum laborum ullam. Doloremque illo quo atque non quam est iusto et. Animi esse sed ut. Ab sed voluptatem aut blanditiis aperiam. Quia laudantium ratione. Et architecto natus officia amet rem. Quae voluptatem quos.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 29,
        tools_and_technologies: [8, 7, 1, 10, 5, 3, 9, 2, 4],
        participants_ids: [],
        job_titles_wanted: [7, 13, 9, 3, 14, 10, 12],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 32,
        user_id: 20,
        created_at: '2023-01-01T00:50:39.008Z',
        updated_at: '2023-01-01T00:50:39.008Z',
        is_online: true,
        project_name: 'Tasha Lockman',
        starting_on: '2022-06-04T04:47:57.717Z',
        full_name: 'Nora Bradtke III',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'month',
        description:
          'Iusto fuga iste velit mollitia. Dolorum perspiciatis saepe. Eligendi natus incidunt quas quos animi. Hic soluta quasi. Id ab atque odio voluptas dolore provident soluta blanditiis. Distinctio quisquam culpa consequatur unde eum est odit quae quo. Quo ut rem quia explicabo sit. Tempore et sed ad ut rerum qui sit velit laboriosam. Suscipit aut et magnam voluptate blanditiis autem assumenda in labore. Aut ea illo. Sunt aliquid neque sunt et consequuntur excepturi ut consequatur.',
        difficulty: 'expert',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 132,
        tools_and_technologies: [9, 7, 8, 3, 10, 2],
        participants_ids: [],
        job_titles_wanted: [10, 2, 8, 11, 14, 4, 3, 9, 7],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 19,
        user_id: 29,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Ana Runolfsson',
        starting_on: '2022-06-06T09:58:24.485Z',
        full_name: 'Michele Bayer',
        estimated_time_duration: 3,
        estimated_time_duration_metric: 'month',
        description:
          'Doloribus earum eum et placeat porro nulla impedit aut. Molestias fugiat harum ipsam veritatis placeat inventore eligendi illum. Consequuntur et ducimus ipsa. Quasi nisi ducimus corrupti ut est et. Rerum aperiam et. Qui harum quia voluptas. Cupiditate perspiciatis occaecati voluptatibus voluptatem quibusdam quasi eius. Fugit necessitatibus debitis quisquam ut ut ea magnam omnis. Perferendis debitis sit ut facere. Non blanditiis provident qui quis et provident et vel sit. Officia sequi et perspiciatis cum tempore alias. Libero itaque molestias eveniet est iure.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 101,
        tools_and_technologies: [5, 9, 7, 8, 4, 2, 1, 6],
        participants_ids: [],
        job_titles_wanted: [11, 4, 9, 15, 14, 5, 2, 12, 6, 8],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 1,
        user_id: 32,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Carolyn Heller',
        starting_on: '2022-07-31T09:42:12.208Z',
        full_name: 'Nathaniel Glover',
        estimated_time_duration: 1,
        estimated_time_duration_metric: 'month',
        description:
          'Est molestiae nesciunt maxime sit. Commodi neque et laudantium placeat enim. Ut ut quo error illum accusamus quia impedit consequatur. Temporibus qui quos quia hic sunt est ab vel. Molestiae doloremque explicabo soluta eos ut perspiciatis. Voluptate possimus quis dolor eum nobis quis at. Nisi harum voluptates expedita officia velit nulla. Sunt doloremque porro ut sint. Voluptates quo veniam quis assumenda corporis quis quia qui tempora. Aliquam voluptas et ut aut quam et hic.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 116,
        tools_and_technologies: [5],
        participants_ids: [],
        job_titles_wanted: [6, 3, 10, 15],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 2,
        user_id: 13,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Melody Wiza',
        starting_on: '2022-06-21T20:07:31.156Z',
        full_name: 'Miss Christine Hintz',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'week',
        description:
          'Velit suscipit iure veritatis voluptatum. Quia quidem assumenda reprehenderit temporibus in. Dolores est excepturi similique aperiam beatae qui cupiditate voluptatem magnam. Voluptas et doloribus aut amet. Iure quaerat quaerat accusantium. Et qui repudiandae. Aut voluptatum fugiat quo. Nostrum voluptas velit voluptatibus rerum. Quia distinctio in repellendus sunt omnis sint sunt rerum est. Rerum asperiores enim recusandae id nobis labore magni rerum perspiciatis. In ut quidem qui pariatur commodi et velit porro dolores. Nihil voluptas natus.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 44,
        tools_and_technologies: [1],
        participants_ids: [],
        job_titles_wanted: [2, 3, 4, 12, 7, 1, 15, 8, 14],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 3,
        user_id: 13,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Elizabeth Schuster',
        starting_on: '2022-06-18T21:25:48.988Z',
        full_name: 'Edwin Kshlerin',
        estimated_time_duration: 8,
        estimated_time_duration_metric: 'month',
        description:
          'Dolor qui atque omnis consequatur fugit non rerum ipsum ullam. Nobis corporis fuga quae sint eum quasi maiores itaque. Vero itaque ratione autem ut. Harum ut excepturi sequi nisi odit. Quo voluptas doloremque eveniet officia aperiam assumenda atque amet assumenda. Numquam dolor esse sed accusantium numquam aut voluptatibus consequatur. Sed ratione est perspiciatis eaque ullam voluptatem recusandae a. Illo et et rem nulla laborum. Quaerat enim itaque culpa. Aperiam reiciendis aut ut dolorum iusto esse.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 46,
        tools_and_technologies: [2, 4, 9, 10, 7, 5, 1, 3],
        participants_ids: [],
        job_titles_wanted: [2, 12, 1, 8, 6, 9, 7, 10, 5, 3, 13],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 4,
        user_id: 30,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'John Reilly',
        starting_on: '2022-06-09T12:00:39.879Z',
        full_name: 'Dr. Rick Wuckert',
        estimated_time_duration: 7,
        estimated_time_duration_metric: 'month',
        description:
          'Inventore eos earum corrupti aut non vel vitae. Labore qui sit sit et quisquam. Quis cum cupiditate asperiores eos et. Aut ullam amet cum. Eum vero adipisci non quod consectetur laboriosam in ullam sit. Consectetur ut earum nisi pariatur officia reiciendis ipsa labore. Laborum quam a doloribus laborum occaecati esse itaque dignissimos. Quia eos in molestiae ipsa repellat iste molestiae laudantium. Accusamus quis sint sint architecto aperiam nostrum. Et deleniti quis fugit eius eaque. Dolorem ut aspernatur. Quod error id eum aliquid dolorem nostrum officia.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 113,
        tools_and_technologies: [8, 10, 1],
        participants_ids: [],
        job_titles_wanted: [1, 3, 4, 8, 12, 5, 15],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 7,
        user_id: 20,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Dean Lind',
        starting_on: '2022-06-03T18:22:56.746Z',
        full_name: "Mr. Denise O'Reilly",
        estimated_time_duration: 10,
        estimated_time_duration_metric: 'week',
        description:
          'Ut minima quia aut aut perferendis ea. Totam ullam ab sit velit itaque praesentium omnis id. At eius in consequatur molestias fuga dolorem et. Blanditiis et nemo non saepe distinctio mollitia. Minima quae cumque nesciunt. Voluptas ea hic architecto. Iste ducimus temporibus laborum sit veritatis dicta. A qui fuga ut. Eos consequatur nostrum voluptatem provident quo possimus ut et veritatis. Quo non tenetur. Ullam rerum cum consectetur ex consequatur omnis. Voluptatem nisi reprehenderit labore animi fugit quas. Et sapiente corrupti voluptatem ut.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 141,
        tools_and_technologies: [6, 5],
        participants_ids: [],
        job_titles_wanted: [3, 11, 12, 8, 13, 9, 15, 2, 6, 10, 4, 14, 5, 7],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 8,
        user_id: 23,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'James Sporer',
        starting_on: '2022-08-04T18:01:59.390Z',
        full_name: 'Victoria Koepp',
        estimated_time_duration: 4,
        estimated_time_duration_metric: 'month',
        description:
          'Rerum voluptas illo qui quibusdam. Autem eum voluptatum earum repudiandae molestiae eos sequi. Dolor harum qui provident hic quisquam minus consectetur laboriosam voluptatum. Pariatur accusantium rem saepe dicta inventore. Dolor enim cupiditate accusantium nihil asperiores nemo. Libero molestias eligendi sint ab fuga. Et beatae soluta sint deleniti incidunt sunt quo veritatis molestias. Totam neque asperiores omnis molestias ea sit eum. Eaque ipsam autem. Aliquid quos ea corporis labore et. Qui numquam accusantium reiciendis. Excepturi quisquam dolor harum perspiciatis nisi. Quia tempora qui quod dolorum voluptates non inventore nisi.',
        difficulty: 'expert',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 110,
        tools_and_technologies: [6, 7, 9, 2, 8, 5, 10, 3],
        participants_ids: [],
        job_titles_wanted: [2, 1, 5],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 9,
        user_id: 31,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Rex Jenkins DDS',
        starting_on: '2022-07-16T15:31:59.465Z',
        full_name: 'Johnny Cassin',
        estimated_time_duration: 6,
        estimated_time_duration_metric: 'week',
        description:
          'Voluptatibus accusantium tempore aut enim. Explicabo delectus ad eos consequuntur possimus a. Et corrupti recusandae occaecati pariatur quaerat. Consequatur qui aperiam unde dicta. Rerum maxime laborum qui voluptatem dignissimos quos. Modi velit autem reiciendis. Consequatur eum quam. Adipisci molestiae aut laborum voluptatem quasi culpa ipsam similique rem. A corporis id est vero dicta architecto aperiam quia. Doloribus est quis omnis et dolorem esse ut.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 2,
        initial_investment: true,
        initial_investment_cost: 122,
        tools_and_technologies: [2, 10, 9, 4, 8, 6, 3, 1, 5, 7],
        participants_ids: [],
        job_titles_wanted: [5, 8, 6, 10, 15, 14, 7],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 10,
        user_id: 27,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Madeline Metz',
        starting_on: '2022-07-26T11:38:22.640Z',
        full_name: 'Ted Harris',
        estimated_time_duration: 10,
        estimated_time_duration_metric: 'week',
        description:
          'Harum illum perspiciatis optio nihil consequatur voluptas ex sunt voluptas. Quis est quam voluptates. Accusantium minus illum. Quam itaque tenetur ipsum asperiores minima hic odit eveniet. Aut omnis at adipisci eligendi magni repellendus explicabo. Asperiores dolorem eaque quos voluptatem. Dolorum porro corporis libero. Quis sint quo qui minima omnis. Debitis quos necessitatibus architecto dolores corporis. Totam quasi beatae asperiores voluptatum voluptas quaerat explicabo itaque. Dolor nam aspernatur qui alias est. Quas voluptatem laborum.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 2,
        initial_investment: true,
        initial_investment_cost: 106,
        tools_and_technologies: [4, 8, 6, 10, 1, 7, 9, 5],
        participants_ids: [],
        job_titles_wanted: [6, 9, 7, 10],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 17,
        user_id: 16,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Robyn Haag',
        starting_on: '2022-07-03T02:04:09.728Z',
        full_name: 'Rudolph Schuster',
        estimated_time_duration: 8,
        estimated_time_duration_metric: 'week',
        description:
          'Officiis pariatur pariatur rerum sint. Quis minima ipsa cupiditate quia nemo occaecati. A voluptatibus rerum enim praesentium dicta enim quia. Commodi sint nihil rerum voluptatem. Provident temporibus labore sint fugit voluptatem vel. Exercitationem voluptas repellendus quia commodi quia. Qui doloremque consequatur vel dignissimos distinctio iusto. Inventore eum quia autem perspiciatis beatae labore ad natus nisi. Aut sit dolorem omnis cupiditate minima vitae eum ab consequatur. Asperiores pariatur ipsum dolor suscipit natus sed possimus quod. Quod aut cumque eos qui dolor. Voluptate rerum aperiam aut odit. Dolores rerum laborum adipisci sit qui.',
        difficulty: 'expert',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: false,
        initial_investment_cost: 57,
        tools_and_technologies: [4],
        participants_ids: [],
        job_titles_wanted: [9, 6, 1, 7, 5, 8, 14, 15, 12, 3],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 21,
        user_id: 10,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Mrs. Jody Keeling',
        starting_on: '2022-07-29T10:06:59.508Z',
        full_name: 'Timothy Shanahan',
        estimated_time_duration: 6,
        estimated_time_duration_metric: 'month',
        description:
          'Sed id maxime perspiciatis modi accusantium aut et autem repudiandae. Amet quod sapiente laboriosam facere. Cupiditate veritatis earum eveniet non illo. Accusantium architecto esse quisquam repellendus. Ut ullam doloremque doloribus. Adipisci distinctio est. Error omnis harum eos ut placeat nam fugit qui. Sit ut nemo magni et impedit similique. Sunt dolore beatae repellendus aut iusto eveniet omnis molestias reiciendis. Est itaque deserunt cumque.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 134,
        tools_and_technologies: [1, 7, 8, 2, 10, 9],
        participants_ids: [],
        job_titles_wanted: [6, 13, 11, 3, 15, 14, 2, 1, 5, 9, 7, 10, 12],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 22,
        user_id: 38,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Timothy Bergnaum',
        starting_on: '2022-07-02T09:19:43.861Z',
        full_name: 'Carolyn Sipes',
        estimated_time_duration: 9,
        estimated_time_duration_metric: 'week',
        description:
          'Voluptatem magni minima qui nisi optio laborum consequatur consectetur deserunt. Ab omnis amet tenetur ratione. Ipsum in ut et nulla veniam dolorem voluptas amet autem. Quod facere similique. Laudantium accusantium quia qui perferendis architecto soluta et vitae. Sint occaecati et eum aut molestias laudantium voluptatem impedit maiores. Saepe dignissimos libero qui ad quaerat. Quisquam fugit laudantium sint quia similique voluptatem quos. Eveniet eaque sunt unde voluptatibus voluptates quasi esse facilis voluptas. Dignissimos sapiente labore quam omnis molestias.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 89,
        tools_and_technologies: [8, 9, 10, 2, 7, 5],
        participants_ids: [],
        job_titles_wanted: [12, 10, 1, 9, 14, 6, 3, 13, 7, 15, 4, 8],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 24,
        user_id: 20,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Lauren Anderson',
        starting_on: '2022-06-24T01:57:04.623Z',
        full_name: 'Daisy Rempel',
        estimated_time_duration: 6,
        estimated_time_duration_metric: 'week',
        description:
          'Et minima tenetur nemo officia optio placeat eum repellendus et. Aspernatur maiores cum sunt quis corrupti delectus. Quos voluptatem assumenda possimus ea id. Voluptates fugit non voluptatum. Officiis asperiores rerum et nobis aut commodi autem unde. Libero modi voluptas rerum blanditiis tempora eum. Vel minima fugit repudiandae enim doloremque nihil illo saepe eum. Occaecati quia recusandae voluptas dolor quo dicta assumenda adipisci perferendis. Voluptatibus aspernatur dolorem qui id reiciendis culpa quia. Eum voluptatum earum. Qui iure dolor iste ut nam error quod ducimus tenetur. Dolor doloribus ut omnis qui quis.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 150,
        tools_and_technologies: [7, 6, 9, 1, 4, 5, 2, 8, 3, 10],
        participants_ids: [],
        job_titles_wanted: [12, 1, 10, 5, 9, 8, 13, 6],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 25,
        user_id: 18,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Mrs. Gayle Gutkowski',
        starting_on: '2022-07-15T10:37:27.300Z',
        full_name: 'Sandra Mann',
        estimated_time_duration: 6,
        estimated_time_duration_metric: 'month',
        description:
          'Tenetur doloremque ex sed iste commodi vero. Dolorem laboriosam corrupti omnis iusto repudiandae. Voluptas eligendi dolor quod velit aut. Placeat molestiae placeat saepe laborum ducimus dolor molestiae minus. Dolore tenetur quia amet aut et dolores. Et voluptas illo quo earum excepturi. Ea doloribus harum veritatis et. Omnis consequatur ea consequatur harum et quo aut assumenda repellat. Ex dignissimos est. Eaque blanditiis sit vitae voluptates sed necessitatibus. Sed dignissimos deleniti ut doloribus explicabo reprehenderit.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 111,
        tools_and_technologies: [9, 2, 8, 5, 6, 3],
        participants_ids: [],
        job_titles_wanted: [1, 3, 2],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 26,
        user_id: 7,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Clifford Marquardt',
        starting_on: '2022-07-26T08:03:02.141Z',
        full_name: 'Darryl Hamill',
        estimated_time_duration: 0,
        estimated_time_duration_metric: 'month',
        description:
          'In recusandae praesentium repudiandae assumenda possimus velit animi porro. Ea exercitationem laboriosam aperiam veniam. Aut vero dolor. Cupiditate minima voluptatum. Voluptatem aliquid veritatis laborum voluptas sunt quaerat enim quia repellat. Sed veritatis accusamus sit et itaque exercitationem voluptas. Et unde explicabo corrupti incidunt nihil. Doloremque quibusdam aut. Ut consequatur laudantium corrupti molestiae ipsa omnis laboriosam suscipit expedita. Autem deserunt aut eveniet ullam. Maxime in et quia quidem vel quibusdam.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 131,
        tools_and_technologies: [7, 6, 8, 9, 5],
        participants_ids: [],
        job_titles_wanted: [8, 3, 7, 10, 14],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 28,
        user_id: 15,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Oscar Rolfson',
        starting_on: '2022-06-25T17:30:07.944Z',
        full_name: 'Dr. Shawna Mohr',
        estimated_time_duration: 5,
        estimated_time_duration_metric: 'week',
        description:
          'Libero modi suscipit expedita molestiae. Qui tempora repudiandae. Doloremque sunt voluptas ut soluta similique. Deleniti laudantium vitae qui. Omnis deserunt beatae. Ut sit quam rem reiciendis laboriosam facilis repellendus voluptatem aut. Sed ex sapiente eos beatae nostrum. Enim aut et error necessitatibus minus nihil. Sit et voluptate itaque. Dolor mollitia aut consectetur rem sunt.',
        difficulty: 'expert',
        type: 'non-profitable',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 125,
        tools_and_technologies: [3, 1],
        participants_ids: [],
        job_titles_wanted: [5, 1, 13, 12, 2, 14, 4, 3, 6, 7, 11, 8],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 23,
        user_id: 4,
        created_at: '2023-01-01T00:50:39.007Z',
        updated_at: '2023-01-01T00:50:39.007Z',
        is_online: true,
        project_name: 'Rebecca Bahringer',
        starting_on: '2022-07-08T10:42:39.087Z',
        full_name: 'Tommy Koss DVM',
        estimated_time_duration: 2,
        estimated_time_duration_metric: 'week',
        description:
          'Praesentium illum architecto. Expedita necessitatibus natus consequatur. Aut sint alias inventore. Necessitatibus inventore nam perferendis. Qui repudiandae quos perspiciatis soluta ut voluptas. Et incidunt quis praesentium iusto non. Tempora et id accusantium. Eos est rerum corrupti eligendi hic odio nemo minima. Similique ipsam fugiat nostrum magni eos natus. Enim minus accusamus autem et. Ipsa ut debitis ullam non perspiciatis ipsa sequi. Eos alias ipsa voluptatem autem non inventore quod.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 103,
        tools_and_technologies: [1, 8, 10, 6, 5, 7],
        participants_ids: [],
        job_titles_wanted: [5, 14, 11, 1, 9, 13, 8, 7, 2, 15, 4],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 12,
        user_id: 10,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Antonia Dach Jr.',
        starting_on: '2022-06-24T22:33:35.867Z',
        full_name: 'Annie Macejkovic',
        estimated_time_duration: 0,
        estimated_time_duration_metric: 'month',
        description:
          'Dolores voluptatibus est labore qui optio illum nobis ut. At voluptatibus et veniam repellat doloribus. Voluptas dolores et perspiciatis reprehenderit. Vitae enim accusantium. Dignissimos ut est omnis quo occaecati reiciendis sed eos. Ut ducimus consequatur tempora occaecati. Suscipit corrupti sit ipsam commodi voluptatem earum. Voluptas voluptatum veritatis dicta voluptatem amet cum vel voluptates voluptatem. Qui animi unde dolorem debitis totam quia aliquam omnis. Dolore exercitationem voluptatem dignissimos iusto sint tempore quis sit. Est odio ut sunt enim. Qui quia doloribus magnam tempore. Tempora velit ut modi quisquam nisi laudantium vitae.',
        difficulty: 'intermediate',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 51,
        tools_and_technologies: [4, 1, 9, 5, 2, 7, 6, 8, 3],
        participants_ids: [],
        job_titles_wanted: [3, 6, 9, 12, 7, 15, 5, 1, 13, 14, 2, 4, 8],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 11,
        user_id: 14,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Bernard Hudson',
        starting_on: '2022-07-20T18:26:31.182Z',
        full_name: 'Randal McCullough',
        estimated_time_duration: 1,
        estimated_time_duration_metric: 'month',
        description:
          'Voluptatem consequuntur unde distinctio autem sit itaque temporibus. Atque ut laboriosam voluptatem praesentium explicabo magni qui quia laborum. Et non voluptatem aut. Unde maiores nulla ut nostrum eaque et. Exercitationem voluptates vel sunt sit maxime earum vitae. Nihil a facilis. Laudantium praesentium aut recusandae quos veritatis sint error enim odit. Omnis quis quam perferendis vitae excepturi placeat nam accusantium. Error perspiciatis enim laboriosam sunt in. Soluta nam quaerat. Eius quod quasi voluptatem placeat aut. Impedit omnis et ratione.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 2,
        initial_investment: true,
        initial_investment_cost: 150,
        tools_and_technologies: [1, 7, 5, 3],
        participants_ids: [],
        job_titles_wanted: [5, 3],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 6,
        user_id: 24,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Douglas Hilpert',
        starting_on: '2022-07-25T04:18:37.894Z',
        full_name: 'Opal Toy',
        estimated_time_duration: 3,
        estimated_time_duration_metric: 'week',
        description:
          'Et sit nulla dolore repudiandae quod est voluptatibus. Rerum sit dignissimos sunt. Dicta nulla dolor. Voluptas expedita voluptas sint enim autem illo sit illo ut. Dolore impedit maiores eos illum quidem ipsum. Ea qui sint ratione dolor. Aut amet vero praesentium sunt totam quia vero aut enim. Doloribus omnis aut perspiciatis modi aspernatur quaerat dolores aut dolores. Possimus dolorem quas sit consequatur. Magnam explicabo natus voluptatibus voluptatum non quis eaque sunt. Voluptatem modi cumque. Et fugiat neque.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 9,
        tools_and_technologies: [2, 9, 10, 5, 1, 3, 7, 8, 6],
        participants_ids: [],
        job_titles_wanted: [3, 14, 15, 11, 1, 10, 12, 7],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 14,
        user_id: 2,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Gayle Bosco',
        starting_on: '2022-07-25T09:06:53.061Z',
        full_name: 'Rosemary Luettgen V',
        estimated_time_duration: 1,
        estimated_time_duration_metric: 'month',
        description:
          'Aliquid est magnam eum dolores dolores eveniet dolorem eligendi. Eius quae omnis cumque optio. Rerum provident quam. Sequi est est placeat ut in quo in qui. Explicabo velit pariatur. Qui et commodi atque ratione laborum est. Aspernatur asperiores sapiente dolore quia quos. Ea non voluptatem vero pariatur quia est porro. Molestias quae est in perspiciatis voluptas blanditiis non sit. Vero voluptatem in rem in sunt aut illo. Eligendi laudantium quos nihil illo cum in corporis mollitia modi.',
        difficulty: 'expert',
        type: 'training project',
        number_of_participants: 3,
        initial_investment: false,
        initial_investment_cost: 102,
        tools_and_technologies: [1, 2, 5],
        participants_ids: [],
        job_titles_wanted: [3, 14, 10, 11, 12, 8, 4, 6, 7, 2, 15, 5, 13, 1],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 20,
        user_id: 33,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Mr. Kenny Swaniawski',
        starting_on: '2022-06-21T20:03:39.229Z',
        full_name: 'Marie Waelchi',
        estimated_time_duration: 8,
        estimated_time_duration_metric: 'week',
        description:
          'Ex dolorum et voluptatibus sequi dolorum. Deleniti iusto natus expedita ipsum enim deserunt. Minima sunt et quo impedit accusamus. Iste esse aspernatur labore praesentium amet. Alias corporis ad aliquid libero animi alias quisquam. Vero nemo culpa cupiditate. Minus ducimus recusandae sapiente ex nihil. Magni esse et. Omnis libero dignissimos et quo nesciunt. Totam soluta officiis dolor sed. Quod velit molestias quas consequatur autem aut aspernatur saepe sequi. Nihil id dolor autem deleniti dolor rerum aut. Blanditiis ab asperiores fugiat.',
        difficulty: 'advanced',
        type: 'training project',
        number_of_participants: 3,
        initial_investment: true,
        initial_investment_cost: 68,
        tools_and_technologies: [7, 5, 6, 9, 1],
        participants_ids: [],
        job_titles_wanted: [7, 15, 8, 10, 14, 9, 1, 11, 13, 4, 6],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a6fe4ee1-5891-4db7-b485-7c3b0747870e-image.jpg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 5,
        user_id: 28,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Doyle Ortiz',
        starting_on: '2022-08-04T12:59:02.692Z',
        full_name: 'Karl Johns',
        estimated_time_duration: 1,
        estimated_time_duration_metric: 'week',
        description:
          'Fugiat esse ut sit. Et qui voluptatem sed debitis vitae voluptas consequatur qui. Quaerat fugiat asperiores ullam eveniet suscipit nobis et iure. Officia deleniti quo illum. Facere earum nostrum et quis neque. Hic incidunt ea. Voluptas omnis beatae doloremque qui. Quaerat optio eaque in maxime quod sit facere alias voluptatem. Autem eveniet soluta autem et animi et et illo. Odit molestiae ut amet impedit doloremque voluptas. Et enim incidunt consequatur commodi nihil quas. Quo velit reprehenderit molestias ullam dignissimos nobis possimus beatae corporis. Et molestiae est.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: true,
        initial_investment_cost: 73,
        tools_and_technologies: [3, 7, 9, 1, 6],
        participants_ids: [],
        job_titles_wanted: [7, 5, 8, 1, 13, 14, 10, 11],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 18,
        user_id: 11,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Rafael Orn DDS',
        starting_on: '2022-06-26T03:39:54.930Z',
        full_name: 'Dr. Timmy Gerhold',
        estimated_time_duration: 8,
        estimated_time_duration_metric: 'week',
        description:
          'Excepturi magnam quas exercitationem quia dicta qui temporibus et sunt. Reiciendis et sed voluptatem culpa consequatur explicabo aliquam laborum. Enim autem odit minus et eum vero recusandae nam. Architecto optio qui molestiae omnis dolorem. Iste dolores itaque tempore. Deleniti facere quae quia ut non voluptatem et enim nihil. Aut aut voluptatibus et nemo neque. Eligendi et facilis. Fuga ut ut. Repellendus minima voluptatem optio consequatur dolor ea. Rem expedita molestiae.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 104,
        tools_and_technologies: [7, 9, 4, 10, 5, 2, 6],
        participants_ids: [],
        job_titles_wanted: [6, 2, 9, 1, 4, 5],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/b7078446-4032-45ec-8029-98fc51995eec-svpp.jpeg',
        ],
      },
      {
        id: 16,
        user_id: 21,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Mrs. Dave Ernser',
        starting_on: '2022-06-06T02:35:53.227Z',
        full_name: 'Lloyd Wisoky I',
        estimated_time_duration: 9,
        estimated_time_duration_metric: 'week',
        description:
          'Necessitatibus et ipsam eligendi veniam officiis libero eos rerum. Unde corrupti quisquam eius atque aliquid quia. Fuga non non ea repellendus. Accusantium non culpa sunt voluptatem aut odio rerum ipsa nemo. Est qui asperiores tenetur ab molestias doloremque praesentium. Et iure aut laudantium nobis veniam. Minus error et numquam quam nostrum aut ut impedit laudantium. Enim vel quae. Quos sapiente sit quam distinctio. Recusandae nihil ducimus in rerum eum voluptatem. Vero ut corporis officia voluptatem reiciendis consectetur consequuntur sed. Repellat nihil labore voluptatem quis quos.',
        difficulty: 'advanced',
        type: 'non-profitable',
        number_of_participants: 2,
        initial_investment: false,
        initial_investment_cost: 33,
        tools_and_technologies: [9, 10, 8, 2, 5, 1, 6, 4, 7],
        participants_ids: [],
        job_titles_wanted: [12, 9, 1, 2, 11, 10, 4, 5, 15, 14, 3],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 15,
        user_id: 21,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Joshua Wilderman II',
        starting_on: '2022-07-26T06:30:22.027Z',
        full_name: 'Dawn Bahringer',
        estimated_time_duration: 10,
        estimated_time_duration_metric: 'week',
        description:
          'Et qui debitis distinctio suscipit fugiat. Sed suscipit aut qui officiis quam quia mollitia voluptatem saepe. Repellendus perferendis harum nam porro error deleniti nulla aut iure. Beatae et perspiciatis hic voluptatem error commodi aut sapiente. Error temporibus veniam molestias doloribus asperiores vel mollitia dicta officiis. Ratione ut blanditiis quaerat soluta dolore. Rerum aut tempora qui ex quis beatae aut optio qui. Sit sunt aut est perferendis rerum voluptas quod. Enim veniam ea consectetur non dignissimos excepturi. Aut aliquid ipsa culpa sit ut temporibus nam. Eum aut voluptatem quos nesciunt. Aut quos at vero.',
        difficulty: 'expert',
        type: 'non-profitable',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 130,
        tools_and_technologies: [8, 9, 4],
        participants_ids: [],
        job_titles_wanted: [5],
        job_titles_filled: [],
        project_main_picture:
          'pictures/a185b63e-09d1-4910-a889-c3da011135de-profile_pic_2.jpeg',
        attachments: [
          'attachments/b11ec556-0198-41f4-8921-11ba428c4353-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
      {
        id: 13,
        user_id: 3,
        created_at: '2023-01-01T00:50:39.005Z',
        updated_at: '2023-01-01T00:50:39.005Z',
        is_online: true,
        project_name: 'Miss Pat Roberts',
        starting_on: '2022-06-21T15:17:17.503Z',
        full_name: 'Monique Wisoky',
        estimated_time_duration: 5,
        estimated_time_duration_metric: 'week',
        description:
          'Nisi illo sed praesentium quidem voluptatem. Blanditiis enim pariatur vel natus fuga perferendis asperiores necessitatibus sit. Iste alias dicta voluptatibus perferendis odio error sit. Esse at exercitationem doloremque voluptatibus consequuntur a nisi aliquam rerum. Ut quo unde vel voluptatem fuga enim. Quia qui est libero eius illum nemo. Voluptatum iure consequatur et quas voluptatem vel sed. Iste aspernatur magnam accusantium rerum odit impedit. Sed neque error illo qui. Quae sit aperiam aut et pariatur eveniet in laboriosam. Veniam omnis praesentium.',
        difficulty: 'intermediate',
        type: 'training project',
        number_of_participants: 1,
        initial_investment: false,
        initial_investment_cost: 45,
        tools_and_technologies: [9, 10],
        participants_ids: [],
        job_titles_wanted: [9, 8, 7, 3, 14, 2, 12],
        job_titles_filled: [],
        project_main_picture:
          'pictures/f933bbbc-5b72-4194-ac1e-84adf42f66fc-svpp.jpeg',
        attachments: [
          'attachments/5fe031da-9847-4831-b0a2-08d30affbd73-domenico-loia-EhTcC9sYXsw-unsplash.jpg',
        ],
      },
    ];
    return this.projectService.getAllProjects(filterProjectDto);
  }

  @Post()
  @UseGuards(JwtAuthGuard)
  @UseInterceptors(
    FileFieldsInterceptor(
      [
        { name: 'project_main_picture', maxCount: 1 },
        { name: 'attachments', maxCount: 5 },
      ],
      multerOptions(),
    ),
  )
  async createNewProject(
    @Body() project: ProjectDto,
    @UploadedFiles()
    files: {
      project_main_picture: Express.Multer.File[];
      attachments: Express.Multer.File[];
    },
    @Request() req,
  ) {
    return this.projectService.createNewProject(files, project, req.user);
  }

  @Delete('delete')
  @UseGuards(JwtAuthGuard)
  async delete(@Body() body: project_idDto, @Request() req) {
    return this.projectService.delete(body.project_id, req.user);
  }

  @Patch()
  @UseGuards(JwtAuthGuard)
  @UseInterceptors(
    FileFieldsInterceptor([
      { name: 'projectPicture', maxCount: 1 },
      { name: 'attachments', maxCount: 5 },
    ]),
  )
  async updateApplicationStatus(
    @Body() project: ProjectDto,
    @UploadedFiles()
    files: {
      projectPicture: Express.Multer.File[];
      attachments: Express.Multer.File[];
    },
    @Request() req,
  ) {
    return this.projectService.updateProject(files, project, req.user);
  }
}
