version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NODE_ENV=development
    volumes:  
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  # api: 
  #   build: 
  #     context: ../apps/api
  #     dockerfile: Dockerfile
  #   ports: 
  #     - 8000:8000
  #   expose: 
  #     - 8000
  #   env_file:
  #     - ../apps/api/environment/dev.env
  #   container_name: api
  #   depends_on: 
  #     - postgres
  #   restart: always
  #   networks:
  #     - backend-network

networks:
  backend-network:
    driver: bridge