version: "3"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    container_name: backend-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=backend
      - NODE_ENV=development
  
volumes:
  postgres:
    name: backend